export const movies = [
  {
    id: "365-days",
    title: "365 Days: This Day",
    image: "/images/movies/movie-1.jpg",
    wallImage: "/images/movies/movie-wall-5.jpg",
    description:
      "Laura and Massimo are back and stronger than ever. But Massimo's family ties and a mysterious man bidding for Laura's heart complicate the lovers' lives.",
    catch: "Love, danger, and desire—can passion survive?",
    rating: 2.7,
    genre: ["Romance", "Drama"],
    streaming: ["Netflix"],
    "release-year": 2022,
  },
  {
    id: "moana-2",
    title: "Moana 2",
    image: "/images/movies/movie-2.jpg",
    wallImage: "/images/movies/movie-wall-1.jpg",
    description:
      "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
    catch: "Beyond the horizon lies an adventure like never before!",
    rating: 6.6,
    genre: ["Adventure", "Animation", "Comedy", "Family"],
    streaming: ["Jiostar"],
    "release-year": 2024,
  },
  {
    id: "mufasa-the-lion-king",
    title: "Mufasa - the Lion King",
    image: "/images/movies/movie-3.jpg",
    wallImage: "/images/movies/movie-wall-2.jpg",
    description:
      "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
    catch: "Before the legend, there was the journey!",
    rating: 6.6,
    genre: ["Adventure", "Animation", "Drama", "Family"],
    streaming: ["Jiostar"],
    "release-year": 2024,
  },
  {
    id: "captain-america-brave-new-world",
    title: "Captain America: Brave New World",
    image: "/images/movies/movie-4.jpg",
    wallImage: "/images/movies/movie-wall-3.jpg",
    description:
      "Sam Wilson, the new Captain America, finds himself in the middle of an international incident and must discover the motive behind a nefarious global plan.",
    catch: "A hero's duty knows no borders!",
    rating: 5.9,
    genre: ["Sci Fi", "Action", "Adventure"],
    streaming: ["Theatres"],
    "release-year": 2025,
  },
  {
    id: "dilwale-dulhania-le-jayenge",
    title: "Dilwale Dulhania Le Jayenge",
    image: "/images/movies/movie-5.jpg",
    wallImage: "/images/movies/movie-wall-4.jpg",
    description:
      "When Raj meets Simran in Europe, it isn't love at first sight but when Simran moves to India for an arranged marriage, love makes its presence felt.",
    catch: "A love story that defies distance, destiny, and tradition!",
    rating: 8.0,
    genre: ["Romance", "Drama", "Family"],
    streaming: ["Prime Video"],
    "release-year": 1995,
  },
  {
    id: "lotr-return-of-the-king",
    title: "The Lord of the Rings: The Return of the King",
    image: "/images/movies/movie-6.jpg",
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    catch: "The fate of Middle-earth is decided in the ultimate battle!",
    rating: 9.0,
    genre: ["Adventure", "Fantasy", "Drama"],
    streaming: ["Prime Video"],
    "release-year": 2003,
  },
  {
    id: "anyone-but-you",
    title: "Anyone But You",
    image: "/images/movies/movie-7.jpg",
    description:
      "After an amazing first date, Bea and Ben's fiery attraction turns ice-cold--until they find themselves unexpectedly reunited at a wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    catch: "Love, laughter, and a fake romance—what could go wrong?",
    rating: 6.1,
    genre: ["Romance", "Comedy"],
    streaming: ["Netflix"],
    "release-year": 2023,
  },
  {
    id: "jumanji-welcome-to-the-jungle",
    title: "Jumanji: Welcome to the Jungle",
    image: "/images/movies/movie-8.jpg",
    description:
      "Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.",
    catch: "Play the game, survive the jungle, and win... or be trapped forever!",
    rating: 7.0,
    genre: ["Adventure", "Comedy", "Action", "Drama"],
    streaming: ["Jiostar", "Netflix"],
    "release-year": 2017,
  },
  {
    id: "the-greatest-showman",
    title: "The Greatest Showman",
    image: "/images/movies/movie-9.jpg",
    description:
      "Celebrates the birth of show business and tells of a visionary who rose from nothing to create a spectacle that became a worldwide sensation.",
    catch: "A dream, a spectacle, and a show like no other!",
    rating: 7.5,
    genre: ["Comedy", "Biography"],
    streaming: ["Prime Video"],
    "release-year": 2017,
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    image: "/images/movies/movie-10.jpg",
    description:
      "The story of J. Robert Oppenheimer and the development of the atomic bomb during World War II.",
    catch: "The man who changed the world—forever.",
    rating: 8.5,
    genre: ["Biography", "Drama", "History"],
    streaming: ["Prime Video"],
    "release-year": 2023,
  },
  {
    id: "barbie",
    title: "Barbie",
    image: "/images/movies/movie-11.jpg",
    description:
      "Barbie and Ken embark on a journey of self-discovery after leaving the perfect world of Barbie Land.",
    catch: "She's everything. He's just Ken.",
    rating: 7.2,
    genre: ["Comedy", "Fantasy", "Adventure"],
    streaming: ["Jiostar"],
    "release-year": 2023,
  },
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    image: "/images/movies/movie-12.jpg",
    description:
      "Paul Atreides unites with the Fremen to seek revenge against those who destroyed his family.",
    catch: "Destiny unfolds on the sands of Arrakis.",
    rating: 8.8,
    genre: ["Sci Fi", "Adventure", "Drama"],
    streaming: ["Theatres"],
    "release-year": 2024,
  },
  {
    id: "pathaan",
    title: "Pathaan",
    image: "/images/movies/movie-13.jpg",
    description:
      "An exiled RAW agent must face his past while stopping a formidable foe planning a massive attack on India.",
    catch: "A patriot. A rebel. A legend returns.",
    rating: 6.9,
    genre: ["Action", "Thriller"],
    streaming: ["Prime Video"],
    "release-year": 2023,
  },
  {
    id: "rocky-aur-rani-ki-prem-kahani",
    title: "Rocky Aur Rani Ki Prem Kahani",
    image: "/images/movies/movie-14.jpg",
    description:
      "A flamboyant Punjabi boy and an intellectual Bengali girl try to win over each other’s families in a cultural clash filled with love and drama.",
    catch: "Love knows no boundaries—especially cultural ones.",
    rating: 7.1,
    genre: ["Romance", "Drama", "Comedy"],
    streaming: ["Jiostar"],
    "release-year": 2023,
  },
  {
    id: "brahmastra",
    title: "Brahmāstra: Part One – Shiva",
    image: "/images/movies/movie-15.jpg",
    description:
      "Shiva, a young man with mysterious powers, discovers his connection to an ancient weapon and a secret society protecting the world.",
    catch: "The beginning of a new cinematic universe of gods and fire.",
    rating: 5.6,
    genre: ["Fantasy", "Action", "Adventure"],
    streaming: ["Jiostar"],
    "release-year": 2022,
  },
  {
    id: "zindagi-na-milegi-dobara",
    title: "Zindagi Na Milegi Dobara",
    image: "/images/movies/movie-16.jpg",
    description:
      "Three friends set out on a road trip in Spain that becomes a journey of self-discovery and emotional healing.",
    catch: "Seize the day. Live the moment. You only live once.",
    rating: 8.2,
    genre: ["Drama", "Adventure", "Romance"],
    streaming: ["Netflix"],
    "release-year": 2011,
  },
  {
    id: "3-idiots",
    title: "3 Idiots",
    image: "/images/movies/movie-17.jpg",
    description:
      "Three engineering students navigate college life and societal expectations, exploring the value of passion over pressure.",
    catch: "Chase excellence, and success will follow.",
    rating: 8.4,
    genre: ["Comedy", "Drama"],
    streaming: ["Prime Video", "Netflix"],
    "release-year": 2009,
  },
  {
    id: "gangubai-kathiawadi",
    title: "Gangubai Kathiawadi",
    image: "/images/movies/movie-18.jpg",
    description:
      "The story of Ganga, who rose to power as Gangubai—a powerful figure in Kamathipura's red-light district, fighting for women's rights.",
    catch: "A woman who ruled a world of men.",
    rating: 7.0,
    genre: ["Biography", "Crime", "Drama"],
    streaming: ["Netflix"],
    "release-year": 2022,
  },
  {
    id: "dangal",
    title: "Dangal",
    image: "/images/movies/movie-19.jpg",
    description:
      "Based on the real-life story of wrestler Mahavir Singh Phogat, who trains his daughters to become world-class wrestlers.",
    catch: "Mhaari chhoriyaan chhoro se kam hain ke?",
    rating: 8.3,
    genre: ["Biography", "Drama", "Sport"],
    streaming: ["Jiostar"],
    "release-year": 2016,
  },
  {
    id: "inception",
    title: "Inception",
    image: "/images/movies/movie-20.jpg",
    description:
      "A skilled thief, the best in the dangerous art of extraction, gets a chance at redemption if he can successfully plant an idea into someone's subconscious.",
    catch: "Your mind is the scene of the crime.",
    rating: 8.8,
    genre: ["Action", "Sci Fi", "Thriller"],
    streaming: ["Netflix", "Prime Video"],
    "release-year": 2010,
  }
];


export const streamingImageMap: Record<string, string> = {
  "Jiostar": "/images/streaming/jiohotstar.png",
  "Netflix": "/images/streaming/netflix.jpg",
  "Prime Video": "/images/streaming/prime.png",
  // Add more platforms here if needed
};