export const series = [
    {
      id: "stranger-things",
      title: "Stranger Things",
      image: "/images/series/series-1.jpg",
      wallImage: "/images/series/series-wall-1.jpg",
      description:
        "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
      catch: "The world is turning upside down.",
      rating: 8.7,
      genre: ["Drama", "Fantasy", "Horror"],
      streaming: ["Netflix"],
      "release-year": 2016,
    },
    {
      id: "the-office",
      title: "The Office",
      image: "/images/series/series-2.jpg",
      wallImage: "/images/series/series-wall-2.jpg",
      description:
        "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
      catch: "Just another day at Dunder Mifflin.",
      rating: 9.0,
      genre: ["Comedy"],
      streaming: ["Prime Video", "Netflix"],
      "release-year": 2005,
    },
    {
      id: "game-of-thrones",
      title: "Game of Thrones",
      image: "/images/series/series-3.jpg",
      wallImage: "/images/series/series-wall-3.jpg",
      description:
        "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros.",
      catch: "Winter is coming.",
      rating: 9.2,
      genre: ["Action", "Adventure", "Drama"],
      streaming: ["Jiostar"],
      "release-year": 2011,
    },
    {
      id: "sherlock",
      title: "Sherlock",
      image: "/images/series/series-4.jpg",
      wallImage: "/images/series/series-wall-4.jpg",
      description:
        "A modern update finds the famous sleuth and his doctor partner solving crime in 21st-century London.",
      catch: "The game is on.",
      rating: 9.1,
      genre: ["Crime", "Drama", "Mystery"],
      streaming: ["Netflix", "Prime Video"],
      "release-year": 2010,
    },
    {
      id: "money-heist",
      title: "Money Heist",
      image: "/images/series/series-5.jpg",
      wallImage: "/images/series/series-wall-5.jpg",
      description:
        "A criminal mastermind who goes by 'The Professor' plans the biggest heist in recorded history—to print billions of euros in the Royal Mint of Spain.",
      catch: "Get ready for the most thrilling robbery of all time.",
      rating: 8.2,
      genre: ["Action", "Crime", "Drama"],
      streaming: ["Netflix"],
      "release-year": 2017,
    },
    {
      id: "breaking-bad",
      title: "Breaking Bad",
      image: "/images/series/series-6.jpg",
      wallImage: "/images/series/series-wall-6.jpg",
      description:
        "A chemistry teacher diagnosed with cancer turns to manufacturing and selling meth to secure his family's future.",
      catch: "Say his name.",
      rating: 9.5,
      genre: ["Crime", "Drama", "Thriller"],
      streaming: ["Netflix"],
      "release-year": 2008,
    },
    {
      id: "the-crown",
      title: "The Crown",
      image: "/images/series/series-7.jpg",
      wallImage: "/images/series/series-wall-7.jpg",
      description:
        "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
      catch: "The royal life exposed.",
      rating: 8.6,
      genre: ["Biography", "Drama", "History"],
      streaming: ["Netflix"],
      "release-year": 2016,
    },
    {
      id: "mirzapur",
      title: "Mirzapur",
      image: "/images/series/series-8.jpg",
      wallImage: "/images/series/series-wall-8.jpg",
      description:
        "A shocking incident at a wedding snowballs into a gang war in the lawless city of Mirzapur.",
      catch: "Power is inherited... or taken.",
      rating: 8.5,
      genre: ["Action", "Crime", "Drama"],
      streaming: ["Prime Video"],
      "release-year": 2018,
    },
    {
      id: "sacred-games",
      title: "Sacred Games",
      image: "/images/series/series-9.jpg",
      wallImage: "/images/series/series-wall-9.jpg",
      description:
        "A troubled police officer finds a link between a missing gangster and a cryptic warning about Mumbai's doom.",
      catch: "The city’s fate lies in one man's hands.",
      rating: 8.6,
      genre: ["Action", "Crime", "Drama"],
      streaming: ["Netflix"],
      "release-year": 2018,
    },
    {
      id: "dark",
      title: "Dark",
      image: "/images/series/series-10.jpg",
      wallImage: "/images/series/series-wall-10.jpg",
      description:
        "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.",
      catch: "Everything is connected.",
      rating: 8.8,
      genre: ["Crime", "Drama", "Mystery"],
      streaming: ["Netflix"],
      "release-year": 2017,
    }
  ];
  