import { randomUUID } from "crypto"

export const walls = [
    {
        "id": randomUUID,
        "title": "Dilwale Dulhania Le Jayenge",
        "image": "/images/movies/movie-wall-4.jpg",
        "description": "When Raj meets Simran in Europe, it isn't love at first sight but when Simran moves to India for an arranged marriage, love makes its presence felt.",
        "catch": "A love story that defies distance, destiny, and tradition!",
    },
    {
        "id": randomUUID,
        "title": "Moana 2",
        "image": "/images/movies/movie-wall-1.jpg",
        "description": "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
        "catch": "Beyond the horizon lies an adventure like never before!",
    },
    {
        "id": randomUUID,
        "title": "Mufasa - the Lion King",
        "image": "/images/movies/movie-wall-2.jpg",
        "description": "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        "catch": "Before the legend, there was the journey!",
    },
    {
        "id": randomUUID,
        "title": "Captain America: Brave New World",
        "image": "/images/movies/movie-wall-3.jpg",
        "description": "Sam Wilson, the new Captain America, finds himself in the middle of an international incident and must discover the motive behind a nefarious global plan.",
        "catch": "A hero's duty knows no borders!",
    },
    {
        "id": randomUUID,
        "title": "365 Days: This Day",
        "image": "/images/movies/movie-wall-5.jpg",
        "description": "Laura and Massimo are back and stronger than ever. But Massimo's family ties and a mysterious man bidding for Laura's heart complicate the lovers' lives.",
        "catch": "Love, danger, and desire—can passion survive?",
    },
    
]

export const movies = [
    {
        "id": randomUUID,
        "title": "365 Days: This Day",
        "image": "/images/movies/movie-1.jpg",
        "description": "Laura and Massimo are back and stronger than ever. But Massimo's family ties and a mysterious man bidding for Laura's heart complicate the lovers' lives.",
        "catch": "Love, danger, and desire—can passion survive?",
        "rating": 2.7,
        "genre": ["Romance", "Drama"],
        "streaming": ["Netflix"],
        "release-year": 2022,
    },
    {
        "id": randomUUID,
        "title": "Moana 2",
        "image": "/images/movies/movie-2.jpg",
        "description": "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
        "catch": "Beyond the horizon lies an adventure like never before!",
        "rating": 6.6,
        "genre": ["Adventure", "Animation", "Comedy", "Family"],
        "streaming": ["Jiostar"],
        "release-year": 2024,
    },
    {
        "id": randomUUID,
        "title": "Mufasa - the Lion King",
        "image": "/images/movies/movie-3.jpg",
        "description": "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        "catch": "Before the legend, there was the journey!",
        "rating": 6.6,
        "genre": ["Adventure", "Animation", "Drama", "Family"],
        "streaming": ["Jiostar"],
        "release-year": 2024,
    },
    {
        "id": randomUUID,
        "title": "Captain America: Brave New World",
        "image": "/images/movies/movie-4.jpg",
        "description": "Sam Wilson, the new Captain America, finds himself in the middle of an international incident and must discover the motive behind a nefarious global plan.",
        "catch": "A hero's duty knows no borders!",
        "rating": 5.9,
        "genre": ["Sci Fi", "Action", "Adventure"],
        "streaming": ["Theatres"],
        "release-year": 2025,
    },
    {
        "id": randomUUID,
        "title": "Dilwale Dulhania Le Jayenge",
        "image": "/images/movies/movie-5.jpg",
        "description": "When Raj meets Simran in Europe, it isn't love at first sight but when Simran moves to India for an arranged marriage, love makes its presence felt.",
        "catch": "A love story that defies distance, destiny, and tradition!",
        "rating": 8.0,
        "genre": ["Romance", "Drama", "Family"],
        "streaming": ["Prime Video"],
        "release-year": 1995,
    },
    {
        "id": randomUUID,
        "title": "The Lord of the Rings: The Return of the King",
        "image": "/images/movies/movie-6.jpg",
        "description": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        "catch": "The fate of Middle-earth is decided in the ultimate battle!",
        "rating": 9.0,
        "genre": ["Adventure", "Fantasy", "Drama"],
        "streaming": ["Prime Video"],
        "release-year": 2003,
    },
    {
        "id": randomUUID,
        "title": "Anyone But You",
        "image": "/images/movies/movie-7.jpg",
        "description": "After an amazing first date, Bea and Ben's fiery attraction turns ice-cold--until they find themselves unexpectedly reunited at a wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
        "catch": "Love, laughter, and a fake romance—what could go wrong?",
        "rating": 6.1,
        "genre": ["Romance", "Comedy"],
        "streaming": ["Netflix"],
        "release-year": 2023,
    },
    {
        "id": randomUUID,
        "title": "Jumanji: Welcome to the Jungle",
        "image": "/images/movies/movie-8.jpg",
        "description": "Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.",
        "catch": "Play the game, survive the jungle, and win... or be trapped forever!",
        "rating": 7.0,
        "genre": ["Adventure", "Comedy", "Action", "Drama"],
        "streaming": ["Jiostar", "Netflix"],
        "release-year": 2017,
    },
    {
        "id": randomUUID,
        "title": "The Greatest Showman",
        "image": "/images/movies/movie-9.jpg",
        "description": "Celebrates the birth of show business and tells of a visionary who rose from nothing to create a spectacle that became a worldwide sensation.",
        "catch": "A dream, a spectacle, and a show like no other!",
        "rating": 7.5,
        "genre": ["Musical", "Comedy", "Biography"],
        "streaming": ["Prime Video"],
        "release-year": 2017,
    },
]